arch:
  - amd64
  - ppc64le
  - s390x
os:
  - linux

services:
  - docker

language: go

go:
  - "1.12"

# branches:
#   only:
#     - master

# Always set the project's Go import path to ensure that forked
# builds get cloned to the correct location.
go_import_path: github.com/IBM/go-repo-template

env:
  global:
    - GO111MODULE=on
    - GOPROXY=https://proxy.golang.org
    - GOLANGCI_LINT_VERSION=v1.18.0

install:
  - |
    # Golangci-lint
    go get github.com/golangci/golangci-lint/cmd/golangci-lint@${GOLANGCI_LINT_VERSION}

script:
  - |
    make lint-go
    make test
    if [[ "$TRAVIS_EVENT_TYPE" != "pull_request" ]]; then
      make build
      make images
    fi

after_script:
  - make clean

# TBD. Suppressing for now.
notifications:
email: false
