arch:
  - amd64
  - ppc64le
  - s390x
os:
  - linux

# Only clone the most recent commit.
git:
  depth: 1

language: go

go:
  - "1.12"

branches:
  only:
    - master

# Always set the project's Go import path to ensure that forked
# builds get cloned to the correct location.
go_import_path: sigs.k8s.io/cluster-api-provider-ibmcloud

before_install:
  - ls

# Skip the install process; let pre-commit.sh do it.
install: true

before_script:
  - ls

script:
  - ls

# TBD. Suppressing for now.
notifications:
email: false
